version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scrapper-stdio-tester
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
      - MCP_SERVER_PORT=0
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    command: >
      sh -c "
        pip install -r requirements.txt;
        echo 'Running all tests...';
        pytest -v -rs tests
      "