version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    command: >
      sh -c "
        echo 'Running all tests...';
        pytest -v -rs tests
      "
    stop_signal: SIGINT
    init: true

  test_mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-mcp
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    command: >
      sh -c "
        echo 'Running only mcp_server tests...';
        pytest -v -rs tests/test_mcp_server.py
      "
    stop_signal: SIGINT
    init: true

  test_scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-scraper
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    command: >
      sh -c "
        echo 'Running only scraper tests...';
        pytest -v -rs tests/test_scraper.py
      "
    stop_signal: SIGINT
    init: true

  test_chunked:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-scraper-tester-chunked
    environment:
      - PYTEST_ADDOPTS=--disable-warnings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./tests:/app/tests
      - ./src:/app/src
    shm_size: '2gb'
    command: >
      sh -c "
        echo 'Running chunked processing tests...';
        pytest -v -rs tests/test_chunked_processing.py tests/test_integration_chunked.py
      "
    stop_signal: SIGINT
    init: true
