name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published, created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: |
      - name: Test Docker build
        run: docker build --no-cache -t web-scrapper-stdio .
          python -m pip install --upgrade pip
          pip install -r requirements.txt 