name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Docker build
        run: docker build --no-cache -t web-scrapper-stdio .
      - name: Update build badge
        if: success()
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d2497a7eb6d0d1a57a4faea9df7c78a1
          filename: gistfile1.txt
          label: build
          message: passing
          color: green
      - name: Update build badge (on failure)
        if: failure()
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d2497a7eb6d0d1a57a4faea9df7c78a1
          filename: gistfile1.txt
          label: build
          message: failing
          color: red
