name: Build, Test & Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published, created]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests (Docker Compose)
        run: docker compose up --build --abort-on-container-exit test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: .
  coverage:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker compose build test
      - name: Run coverage in container
        run: docker compose run --rm -T -v ${{ github.workspace }}:/app test pytest --cov=src --cov-report=term --cov-report=json:/app/coverage.json
      - name: Extract coverage percent
        run: |
          COVERAGE=$(python -c "import json; print(json.load(open('coverage.json'))['totals']['percent_covered_display'])")
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      - name: Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: <your-gist-id>
          filename: web-scrapper-stdio_coverage.json
          label: coverage
          message: ${{ env.COVERAGE }}%
          color: green 