name: Test on Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  docker-tests:
    name: Run Scraper and MCP Tests in Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build all test images
        run: |
          docker compose build test_scrapper test_mcp

      - name: Run Scraper tests
        run: |
          docker compose up --abort-on-container-exit --build test_scrapper | tee test-scrapper-output.log

      - name: Show Scraper test summary (even on failure)
        if: always()
        run: cat test-scrapper-output.log || true

      - name: Clean up Docker resources (scrapper)
        if: always()
        run: docker compose down -v || true

      - name: Run MCP server tests
        run: |
          docker compose up --abort-on-container-exit --build test_mcp | tee test-mcp-output.log

      - name: Show MCP test summary (even on failure)
        if: always()
        run: cat test-mcp-output.log || true

      - name: Clean up Docker resources (mcp)
        if: always()
        run: docker compose down -v || true 